OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: tfs.at2chain.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer.tfs.at2chain.com
        CommonName: orderer.tfs.at2chain.com

PeerOrgs:

  - Name: Org1
    Domain: org1.tfs.at2chain.com

    Specs:
      - Hostname: peer0.org1.tfs.at2chain.com
        CommonName: peer0.org1.tfs.at2chain.com

  - Name: Org2
    Domain: org2.tfs.at2chain.com

    Specs:
      - Hostname: peer0.org2.tfs.at2chain.com
        CommonName: peer0.org2.tfs.at2chain.com

  - Name: Org3
    Domain: org3.tfs.at2chain.com

    Specs:
      - Hostname: peer0.org3.tfs.at2chain.com
        CommonName: peer0.org3.tfs.at2chain.com
  
