version: '2'

services:

  orderer.tfs.at2chain.com:
    container_name: orderer.tfs.at2chain.com
    image: hyperledger/fabric-orderer:1.3.0
    restart: always
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - GODEBUG=netdns=go
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - /mnt/fabric/orderer:/var/hyperledger/production
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/tfs.at2chain.com/orderers/orderer.tfs.at2chain.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/tfs.at2chain.com/orderers/orderer.tfs.at2chain.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  peer0.org1.tfs.at2chain.com:
    container_name: peer0.org1.tfs.at2chain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.tfs.at2chain.com
      - CORE_PEER_ADDRESS=peer0.org1.tfs.at2chain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.tfs.at2chain.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - GODEBUG=netdns=go
    volumes:
        - /var/run/:/host/var/run/
        - /mnt/fabric/peer0.org1:/var/hyperledger/production
        - ../crypto-config/peerOrganizations/org1.tfs.at2chain.com/peers/peer0.org1.tfs.at2chain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.tfs.at2chain.com/peers/peer0.org1.tfs.at2chain.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053

  peer0.org2.tfs.at2chain.com:
    container_name: peer0.org2.tfs.at2chain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.tfs.at2chain.com
      - CORE_PEER_ADDRESS=peer0.org2.tfs.at2chain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.tfs.at2chain.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.tfs.at2chain.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - GODEBUG=netdns=go
    volumes:
        - /var/run/:/host/var/run/
        - /mnt/fabric/peer0.org2:/var/hyperledger/production
        - ../crypto-config/peerOrganizations/org2.tfs.at2chain.com/peers/peer0.org2.tfs.at2chain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.tfs.at2chain.com/peers/peer0.org2.tfs.at2chain.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8053:7053

  peer0.org3.tfs.at2chain.com:
    container_name: peer0.org3.tfs.at2chain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org3.tfs.at2chain.com
      - CORE_PEER_ADDRESS=peer0.org3.tfs.at2chain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.tfs.at2chain.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.tfs.at2chain.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
      - GODEBUG=netdns=go
    volumes:
        - /var/run/:/host/var/run/
        - /mnt/fabric/peer0.org3:/var/hyperledger/production
        - ../crypto-config/peerOrganizations/org3.tfs.at2chain.com/peers/peer0.org3.tfs.at2chain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org3.tfs.at2chain.com/peers/peer0.org3.tfs.at2chain.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053

